# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet build MentorAPI
    - name: Restore dependenciesTest
      run: dotnet build TestProject
    - name: Restore dependenciesTest1
      run: dotnet build TestProject1
    - name: Test
      run: dotnet test TestProject --no-build --verbosity normal
    - name: Test1
      run: dotnet test TestProject1 --no-build --verbosity normal
